import localFont from "next/font/local";
// import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import Link from "next/link";

export default function RootLayout({ children }) {
    return (
        <html lang="pl">
        <head>
            <title>Aplikacja Pokemon</title>
        </head>
        <body>
        <header>
            <h1>Aplikacja Pokemon</h1>
            <nav>
                <Link href="/">Strona główna</Link> |{" "}
                <Link href="/pages/pokemon-list">Lista Pokémonów</Link> |{" "}
            </nav>
        </header>
        <main>{children}</main>
        <footer>
            <p>Autor: Szymon Baniewicz</p>
        </footer>
        </body>
        </html>
    );
}

